version: "3.7"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    image: demo_odoo_18
    container_name: demo_odoo_18
    network_mode: bridge
    ports:
      - "7008:8069"
    volumes:
      - data:/var/lib/odoo
    environment:
      HOST: "host.docker.internal"
      USER: "demo_odoo_18"
      PASSWORD: "o"
    extra_hosts:
      - "host.docker.internal:host-gateway"
